server:
  port: 8080
# cors Configs 
cors:
  originPatterns: http://localhost:3000,http://localhost:8080,http://localhost:80

# jwt spring security Configs 
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
        
# spring Configs        
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/rest_with_spring_boot_udemy?useTimezone=true&serverTimezone=UTC
        username: root
        password: admin123
    
    # Jackson Configs
    jackson:
        default-property-inclusion: NON_NULL

    jpa:
        hibernate: 
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect

        show-sql: false
        
# Flyway Configs
flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: rest_with_spring_boot_udemy
    user: root
    password: admin123
    
#Swagger Configs
springdoc:
    pathsToMatch: 
        - /auth/**
        - /api/**/v1/**
    swagger-ui:
        use-root-path: true
      