name: Java CI with Git Hub Actions

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2.1.0
      with:   
        username: ${{ secrets.DOCKER_USERNAME }}   
        password: ${{ secrets.DOCKER_PASSWORD }}    
    
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'adopt'
        cache: maven
        
    - name: Build with Maven
      working-directory: ./rest-with-spring-boot-and-java\restWithSpringBootUdemy
      run: |
        - pwd
        - mvn clean package
      
    - name: Build with Docker Compose
      working-directory: ./rest-with-spring-boot-and-java
      run: docker compose build    
      
    - name: Push to Docker Hub
      run: docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-udemy:latest ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-udemy:${{ github.run_id }}     
           docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-udemy:${{ github.run_id }}
           docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-udemy:latest

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
